### ISSUE TITLE
Having & in the commit message fails deployment

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/action-store-release#1]
You get the following message if the commit message contains the `&` char:

```
Run Codeinwp/action-store-release@main
⬤  debug     Starting commit verification!
⬤  debug     No commit found!
⬤  debug     Status Code: 200
⬤  debug     Body:  {
  code: 'rest_invalid_json',
  message: 'Invalid JSON body passed.',
  data: {
    status: 400,
    json_error_code: 3,
    json_error_message: 'Control character error, possibly incorrectly encoded'
  }
}
```

Couple of examples where it failed:

- https://github.com/Codeinwp/hyve/commit/41060b7913d7505e8ed1650f519481ef9b66f25d
- https://github.com/Codeinwp/tweet-old-post-pro/commit/a8c7e3b6160f3f44fbfaa0a5ad551a72e1302ee5

**Comment by selul** [comment]
fixed it, the error was with the quotes and apostrophes in the messages, not &
